version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: db-client
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: db-client
    target-branch: main
