name: navigator-admin-backend-dev
services:
  webapp:
    command: poetry run fastapi dev --port 8888 --host 0.0.0.0
    build:
      context: ./
      dockerfile: Dockerfile.webapp
    tty: true
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8888:8888
    env_file:
      - .env
    environment:
      PYTHONPATH: .
      ADMIN_POSTGRES_HOST: postgres
      ADMIN_POSTGRES_USER: navigator_admin
      ADMIN_POSTGRES_DATABASE: navigator
      ADMIN_POSTGRES_PASSWORD: password
      SECRET_KEY: secret_test_key
      LOG_LEVEL: DEBUG

      # Bulk import
      SLACK_WEBHOOK_URL: skip
      BULK_IMPORT_BUCKET: bulk-import-bucket

      # Db dump
      DATABASE_DUMP_BUCKET: database-dump-bucket

      # Presigned URLs
      CACHE_BUCKET: cache-bucket
      CDN_URL: https://cdn.test.com

      # localstack
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localstack:4566
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_started

  postgres:
    environment:
      POSTGRES_DB: navigator
      POSTGRES_PASSWORD: password
      POSTGRES_USER: navigator_admin
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    volumes:
      - ./dumps/navigator.sql:/docker-entrypoint-initdb.d/navigator.sql
    healthcheck:
      test: [CMD-SHELL, "pg_isready -U ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - 5432:5432

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-dev}"
    image: localstack/localstack:s3-latest
    ports:
      - 4566:4566 # LocalStack Gateway
    environment:
      DEBUG: ${DEBUG:-0}
      # These values are used by the init-s3.py script
      BULK_IMPORT_BUCKET: bulk-import-bucket
      DATABASE_DUMP_BUCKET: database-dump-bucket
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localhost:4566
    volumes:
      - ./tests/integration_tests/init-s3.py:/etc/localstack/init/ready.d/init-s3.py
