services:
  webapp:
    command: poetry run pytest --disable-warnings ${TEST}
    build:
      context: ./
      dockerfile: Dockerfile.webapp
    tty: true
    volumes:
      - ./tests:/usr/src/tests
    environment:
      PYTHONPATH: .
      ADMIN_POSTGRES_HOST: postgres
      ADMIN_POSTGRES_USER: navigator_admin
      ADMIN_POSTGRES_PASSWORD: password
      ADMIN_POSTGRES_DATABASE: navigator
      PGUSER: navigator_admin
      PGPASSWORD: password
      PGHOST: postgres
      PGDATABASE: navigator
      SECRET_KEY: ???
      # API_HOST: http://navigator-admin-backend:8888
      # This is for when people explicitly set the tests they want to run
      # It is used in the makefile
      TEST: ${TEST}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    environment:
      POSTGRES_USER: navigator_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: navigator
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    healthcheck:
      test: [CMD-SHELL, "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 30
