version: '3.7'
services:
  admin_backend_db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - admin-data:/var/lib/postgresql/data:cached
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"  ]
      interval: 5s
      timeout: 3s
      retries: 30

  navigator-admin-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: navigator-admin-backend
    tty: true
    env_file:
      - .env
    volumes:
      - ./:/cpr-admin-backend/:cached
    ports:
      - 8888:8888
    environment:
      PYTHONPATH: .
    depends_on:
      admin_backend_db:
        condition: service_healthy


volumes:
  admin-data:
