FROM python:3.10-slim

WORKDIR /usr/src
ENV PYTHONPATH=/usr/src

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    postgresql-client && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir poetry==1.7.1
COPY poetry.lock pyproject.toml ./
RUN poetry config virtualenvs.create false && poetry install --no-directory --no-root

COPY ./app ./app
CMD python app/main.py
