name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# https://github.com/marketplace/actions/docker-layer-caching
jobs:
  test-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: make test_bashscripts

  build-start-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install "poetry==1.6.1" && poetry install && poetry run pre-commit install

      - name: Run pre-commit checks
        run: |
          poetry run pre-commit run --all-files

      - name: Build
        run: make build

      - name: Run Unit Tests
        run: make unit_test

      - name: Run Integration Tests
        run: make integration_test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.6.1

      - name: Push Images to ECR
        run: |
          .github/retag-and-push.sh navigator-admin-backend latest
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
