name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# https://github.com/marketplace/actions/docker-layer-caching
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install "poetry==1.6.1" && poetry install && poetry run pre-commit install

      - name: Run pre-commit checks
        run: |
          poetry run pre-commit run --all-files

      - name: Check code contains no FIXME's
        run: |
          git grep -r --no-color ${case_sensitive} --line-number -e "FIXME" :^.github
          if [[ $? -eq 0 ]]; then
            # if we found any FIXME entries in checked in files, fail on main
            exit 1
          else
            exit 0
          fi
        shell: bash {0}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure test env variables
        run: cp .env.example .env

      - name: Test bash scripts
        run: make test_bashscripts

      - name: Run Unit Tests
        run: make unit_test

      - name: Run Integration Tests
        run: make integration_test

  build:
    runs-on: ubuntu-latest
    needs:
      - code-quality
      - test
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.6.1

      - name: Push Images to ECR
        run: |
          .github/retag-and-push.sh navigator-admin-backend latest
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}