name: Debug

on:
  workflow_dispatch

# https://github.com/marketplace/actions/docker-layer-caching
jobs:
  tag:
    uses: climatepolicyradar/reusable-workflows/.github/workflows/tag.yml@main
    with:
      repo-name: navigator-admin-backend
      semver-tag: main-${GITHUB_SHA::8}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

  release:
    needs: tag
    uses: climatepolicyradar/reusable-workflows/.github/workflows/release.yml@main
    with:
      new_tag: ${{ needs.tag.outputs.new_tag }}
