name: main push autotag

on:
  push:
    branches:
      - main

jobs:
  auto-git-tag:
    runs-on: ubuntu-latest

    # Expose step outputs as job outputs
    outputs:
      new_tag: ${{ steps.run_git_auto_tag.outputs.new_tag }}

    steps:
    - uses: actions/github-script@v6
      id: get_pr_data
      with:
        script: |
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0];

    - uses: actions/checkout@v2
    - uses: fregante/setup-git-user@v2
    - name: Run Auto-tagging
      id: run_git_auto_tag
      # User controlled input needs to be santitised beforehand e.g., by adding an
      # intermediate env var to prevent the workflow being exposed to a critical
      # command injection attack
      env:
        PR_BODY: '${{ fromJson(steps.get_pr_data.outputs.result).body }}'
        PR_NUMBER: '${{ fromJson(steps.get_pr_data.outputs.result).number }}'
      run: |
        echo "Attempting to auto-tag merge commit"
        new_tag=$(.github/auto-tag.sh "${PR_BODY}" "${PR_NUMBER}")
        echo "new_tag=${new_tag}"  >> "$GITHUB_OUTPUT"

  auto-semver-tag:
    needs: auto-git-tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.6.1

      - name: Docker pull, retag and push
        env:
          NEW_TAG: ${{needs.auto-git-tag.outputs.new_tag}}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          .github/retag-and-push.sh navigator-admin-backend main-${GITHUB_SHA::8}
