name: main push git autotag

on:
  push

jobs:
  auto-git-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: get_pr_data
      with:
        script: |
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0];

    - name: Pull Request data
      run: |
        echo '${{ fromJson(steps.get_pr_data.outputs.result).number }}'
        echo '${{ fromJson(steps.get_pr_data.outputs.result).title }}'
        echo '${{ fromJson(steps.get_pr_data.outputs.result).body }}'

