name: Merge to main
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: merge-to-main-deploy
  cancel-in-progress: false

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy-staging.yml
    secrets: inherit

  deploy-production:
    needs: deploy-staging
    uses: ./.github/workflows/deploy-production.yml
    secrets: inherit
