name: Auto-Tag

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  auto-git-and-semver-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Test conditions
      run: |
        echo ${{ github.ref }}
        echo ${{ github.ref == 'refs/heads/main' }}
        echo ${{ github.event.workflow_run.conclusion }}
        echo ${{ github.event.workflow_run.conclusion == 'success' }}
        echo ${{ github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success' }}

  semver-for-manually-created-tags:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker pull, retag and push
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          docker pull ${DOCKER_REGISTRY}/navigator-admin-backend:main-${GITHUB_SHA::8}
          docker tag ${DOCKER_REGISTRY}/navigator-admin-backend:main-${GITHUB_SHA::8}  navigator-admin-backend:main-${GITHUB_SHA::8}
          .github/retag-and-push.sh navigator-admin-backend main-${GITHUB_SHA::8}
